Bump wordpress/blocks to latest to address error
To address JS error TypeError: Object(...) is not a function

This is from:
    var sanitizedAttributes = attributes && __experimentalSanitizeBlockAttributes(block, attributes); // If httpMethod is 'POST', send the attributes in the request body instead of the URL.