Bump wordpress/block-editor in response to failed Jest tests
There as a CircleCI error:
Cannot find module '../block-title' from 'index.js'
    Require stack:
      node_modules/@wordpress/block-editor/build/components/block-breadcrumb/index.js